In [152]:
from scipy import signal
import cv2
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam
import tensorflow as tf
from PIL import Image
from sklearn.metrics import confusion_matrix
from keras.datasets import mnist
from keras.utils import to_categorical
import pathlib

In [91]:
trainbatches = ImageDataGenerator(rescale= 1./255).flow_from_directory('imgs/train',\
                                                                       target_size=(100,200), \
                                                                       #classes=['0','1','-1','2','-2','3','-3'],\
                                                                      batch_size=50)
validatebatches = ImageDataGenerator(rescale= 1./255).flow_from_directory('imgs/validate',\
                                                                       target_size=(100,200), \
                                                                       #classes=['0','1','-1','2','-2','3','-3'],\
                                                                      batch_size=45)
testbatches = ImageDataGenerator(rescale = 1./255).flow_from_directory('imgs/test',\
                                                                      target_size=(100,200),\
                                                                      #classes=['0','1','-1','2','-2','3','-3'],\
                                                                      batch_size=64);
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
X_train = X_train/255
X_test = X_test/255
classifier = Sequential();
classifier.add(Conv2D(64,(3,3),activation = 'relu', input_shape = (100,200,3)))
classifier.add(MaxPooling2D(pool_size = (2,2)))
classifier.add(Dropout(0.5))
classifier.add(Conv2D(32,(3,3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2,2)))
classifier.add(Dropout(0.5))
classifier.add(Conv2D(28,(3,3),activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2,2)))
classifier.add(Dropout(0.5))
classifier.add(Flatten())
classifier.add(Dropout(0.5))
classifier.add(Dense(7,activation = 'softmax'))
#sgd = SGD(lr = 0.001,momentum = 0.9)
classifier.compile(optimizer='adam', loss = 'categorical_crossentropy' ,metrics = ['accuracy'])

Found 1755 images belonging to 7 classes.
Found 181 images belonging to 7 classes.
Found 64 images belonging to 7 classes.


In [92]:
classifier.fit_generator(trainbatches, steps_per_epoch = 32, validation_data = validatebatches, validation_steps = 4, epochs = 103)
#classifier.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Epoch 1/103
32/32 [==============================] - 36s 1s/step - loss: 1.8573 - acc: 0.2369 - val_loss: 1.8968 - val_acc: 0.2667
Epoch 2/103
32/32 [==============================] - 33s 1s/step - loss: 1.7321 - acc: 0.2809 - val_loss: 1.7548 - val_acc: 0.3676
Epoch 3/103
32/32 [==============================] - 34s 1s/step - loss: 1.6469 - acc: 0.3197 - val_loss: 1.6329 - val_acc: 0.4265
Epoch 4/103
32/32 [==============================] - 34s 1s/step - loss: 1.5815 - acc: 0.3464 - val_loss: 1.7256 - val_acc: 0.2941
Epoch 5/103
32/32 [==============================] - 33s 1s/step - loss: 1.5462 - acc: 0.3744 - val_loss: 1.6557 - val_acc: 0.3088
Epoch 6/103
32/32 [==============================] - 37s 1s/step - loss: 1.3849 - acc: 0.4120 - val_loss: 1.4300 - val_acc: 0.4111
Epoch 7/103
32/32 [==============================] - 36s 1s/step - loss: 1.3411 - acc: 0.4396 - val_loss: 1.4220 - val_acc: 0.4926
Epoch 8/103
32/32 [==============================] - 35s 1s/step - loss: 1.2138 - a

32/32 [==============================] - 35s 1s/step - loss: 0.4128 - acc: 0.8480 - val_loss: 0.8395 - val_acc: 0.6544
Epoch 64/103
32/32 [==============================] - 35s 1s/step - loss: 0.4384 - acc: 0.8225 - val_loss: 0.5296 - val_acc: 0.8015
Epoch 65/103
32/32 [==============================] - 35s 1s/step - loss: 0.4225 - acc: 0.8342 - val_loss: 0.4472 - val_acc: 0.8824
Epoch 66/103
32/32 [==============================] - 35s 1s/step - loss: 0.4601 - acc: 0.8280 - val_loss: 0.6615 - val_acc: 0.7389
Epoch 67/103
32/32 [==============================] - 34s 1s/step - loss: 0.4482 - acc: 0.8325 - val_loss: 0.4993 - val_acc: 0.8309
Epoch 68/103
32/32 [==============================] - 34s 1s/step - loss: 0.4716 - acc: 0.8233 - val_loss: 0.5969 - val_acc: 0.7647
Epoch 69/103
32/32 [==============================] - 35s 1s/step - loss: 0.4711 - acc: 0.8194 - val_loss: 0.7136 - val_acc: 0.7059
Epoch 70/103
32/32 [==============================] - 36s 1s/step - loss: 0.4015 - acc: 0

In [89]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_77 (Conv2D)           (None, 98, 198, 64)       1792      
_________________________________________________________________
max_pooling2d_59 (MaxPooling (None, 49, 99, 64)        0         
_________________________________________________________________
dropout_65 (Dropout)         (None, 49, 99, 64)        0         
_________________________________________________________________
conv2d_78 (Conv2D)           (None, 47, 97, 32)        18464     
_________________________________________________________________
max_pooling2d_60 (MaxPooling (None, 23, 48, 32)        0         
_________________________________________________________________
dropout_66 (Dropout)         (None, 23, 48, 32)        0         
_________________________________________________________________
conv2d_79 (Conv2D)           (None, 21, 46, 28)        8092      
__________

In [94]:
#Saving Model
classifier_json = classifier.to_json();
with open("classifier2.json","w") as json_file:
    json_file.write(classifier_json)
classifier.save_weights("classifier2.h5")

In [174]:
testbatches = ImageDataGenerator(rescale = 1./255).flow_from_directory('faulty/test',\
                                                                      target_size=(100,200),\
                                                                      #classes=['0','1','-1','2','-2','3','-3'],\
                                                                      batch_size=162);

Found 100 images belonging to 7 classes.


In [175]:
testimgs,testlabels = next(testbatches);
print(np.shape(testimgs))
print(testlabels)
print('\n\n')
#prediction = classifier.predict_generator(testbatches,steps=1)
prediction = classifier.predict(testimgs)
print(prediction.round())

(100, 100, 200, 3)
[[0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0

In [176]:
test_acc = 0
row = []
confusion_matrix = np.zeros((7,8));
for i in range(prediction.shape[0]):
    if (np.array_equal((prediction[i,:]).round(),testlabels[i,:])):
        test_acc += 1
        which_rate = 0
        for j in range(prediction.shape[1]):
            if(testlabels[i,j] == 1):
                which_rate = j
        confusion_matrix[which_rate,which_rate] += 1;
    else:
        row.append(i)
        which_rate_right = 0
        which_rate_wrong2 = 7
        for j in range(prediction.shape[1]):
            if((prediction[i,j]).round() == 1):
                which_rate_wrong2 = j;
        for j in range(prediction.shape[1]):
            if(testlabels[i,j] == 1):
                which_rate_right = j;
        confusion_matrix[which_rate_right, which_rate_wrong2] += 1

In [177]:
print(test_acc / prediction.shape[0])
print(row)
print(confusion_matrix)

0.63
[0, 1, 2, 4, 7, 12, 13, 14, 15, 17, 18, 21, 22, 24, 27, 32, 38, 40, 44, 46, 51, 55, 57, 58, 61, 62, 66, 76, 78, 79, 83, 85, 87, 90, 92, 94, 98]
[[11.  1.  1.  6.  0.  0.  0.  1.]
 [ 3.  6.  0.  0.  0.  0.  0.  1.]
 [ 2.  0.  5.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. 21.  4.  0.  0.  0.]
 [ 0.  0.  0.  6. 11.  0.  2.  1.]
 [ 0.  0.  0.  0.  3.  2.  5.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.]]


In [165]:
cv2.imshow('which one failed',np.uint8(testimgs[57,:,:,:]*255));
cv2.waitKey(0)
cv2.destroyAllWindows()

In [166]:
for i in row:
    im = Image.fromarray(np.uint8(testimgs[i,:,:,:]*255));
    im.save(pathlib.Path.cwd()/'classifier2_failed_imgs'/('Outdoor_' + str(i) + '.tif'))

In [172]:
print((prediction.round())[85])

[0. 0. 0. 1. 0. 0. 0.]


In [173]:
print((testlabels[85]))

[1. 0. 0. 0. 0. 0. 0.]
